# Generated by Django 2.2.5 on 2019-09-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=300)),
            ],
        ),
    ]
